name: Basic Test

on:
  push:
    branches:
    - '*'

jobs:
  BasicTest:
    name: Python test
    runs-on: ubuntu-latest

    steps:
    - name: Test exit
      shell: bash {0} '-u'
      run: |
        x=1
        while [ $x -le 10 ]
        do
          coproc { exit 49; }
          wait $COPROC_PID
          RETVAL=$?
          echo "$RETVAL"
      
          if [ $RETVAL -eq 0 ]; then
            echo "eq 0"
            break
          fi
          echo "NN"
          x=$(( $x + 1 ))
        done
