name: Basic_action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main CAT repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        path: main

    - name: Checkout second GITHUB pages repository
      uses: actions/checkout@v2
      with:
        repository: machinekit/machinekit.github.io
        fetch-depth: '1'
        path: second

    - name: Checkout third GITHUB pages repository
      uses: actions/checkout@v2
      with:
        repository: machinekit/machinekit-hal
        fetch-depth: '0'
        path: third

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        pwd
        ls
        echo +++
        ls main
        echo ---
        ls second
        echo ***
        ls third
        cd main
        git log --oneline --max-count 10
        cd ../third
        git log --oneline --max-count 10

