name: Jekyll_build_action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main CAT repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '1'
        path: main-cat

    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: cerna/cerna.github.io
        fetch-depth: '1'
        path: target

    - name: Run a Jekyll builder
      run: docker run -v $(pwd)/main-cat:/work haberlerm/docker-jekyll-asciidoctor jekyll build --verbose --trace --config _config.yml,_config_devel.yml

    - name: Run a multi-line script
      run: |
        echo VYPIS obsah vytvorene slozky
        ls -R main-cat/_site
        cp -r main-cat/_site target
        echo +++++++
        ls -R target

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: target