name: Jekyll_build_action_push_on_master

on:
  push:
    branches:
      - mk-docs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: hub example
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pr list  # list pull requests in the current repo
        bin/hub version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout main CAT repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '1'
        path: main-cat

    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: cerna/cerna.github.io
        fetch-depth: '1'
        path: target

    - name: Run a multi-line script
      run: |
        echo VYPIS obsah vytvorene slozky
        ls -R main-cat/_site
        touch ./target/${{ github.sha }}.txt
        echo +++++++
        ls -R target
        echo KONEC
      
    - name: Create commit
      run: |
        git config --local user.email "neco@neco.pl"
        git config --local user.name "Jan Novotný"
        git status
        git add --all
        git commit -m "Message x"
      working-directory: ./target

    - name: hub example
      shell: bash
      run: |
        bin/hub version
        hub push 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./target
    
