name: Basic action

on: 
  push:
    branches:
      - '*'

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Machinekit-HAL repository
      uses: actions/checkout@v2
      with:
        ref: '${{ github.event.ref }}'
        path: 'build/machinekit-hal'

    - uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        username: 'cerna'
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: cerna/cerna-testing-actions/basic.image
        tags: latest
        dockerfile: 'build/machinekit-hal/Dockerfile'