name: Jekyll_build_action_pull_on_mk-docs

on:
  pull_request:
    branches:
      - mk-docs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main CAT repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '1'
        path: main-cat

    - name: Checkout CAT repository, gh_pages branch
      uses: actions/checkout@v2
      with:
        ref: gh_pages
        fetch-depth: '1'
        path: target

    - name: Run a Jekyll builder
      run: docker run -v $(pwd)/main-cat:/work haberlerm/docker-jekyll-asciidoctor jekyll build --verbose --trace --config _config.yml,_config_devel.yml

    - name: Run a multi-line script
      run: |
        echo VYPIS obsah vytvorene slozky
        ls -R main-cat/_site
        cp -r main-cat/_site/* target/
        echo +++++++
        ls -R target
        echo KONEC
    
    - name: Create commit
      run: |
        cd target
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        git commit -m "Dodelat"

    - name: Push changes to gh_pages
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh_pages