name: Basic action

on: 
  push:
    branches:
      - '*'

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        username: 'cerna'
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: cerna/cerna-testing-actions
        tags: latest