name: Show payload

on:
  push:
    branches:
      - '*'

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Show payload
        run: |
          jq '.' $GITHUB_EVENT_PATH

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${{ env.GITHUB_CONTEXT }}"

      - name: Test before ${{ github.event.before }}
        run: |
          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            echo "This is new branch or tag push"
          fi

      - name: Show size
        run: |
          echo "${{ github.event.before }}"
          echo "${{ github.event }}"
          echo "${{ github.event.ref }}"
          echo "${{ github.ref }}"
          echo "${{ github.event.size }}"
          echo "$${{ github.event.size }}"
          echo $$${{ github.event.size }}
          echo "${{ github.event.push.size }}"
          echo "${{ github.event.push.*.size }}"
          jq '.commits | length' ${{ github.event_path }}
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          #ref: ${{ github.event.ref }}
          path: 'testing'
          fetch-depth: ''
      - name: Run only
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | xargs  
        working-directory: ./testing
      - name: Export changed
        id: filepath
        run: |
          echo ::set-output name=commitpath::$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | xargs)
        working-directory: ./testing
      - name: Show changed paths
        run: |
          echo ${{ steps.filepath.outputs.commitpath }}

      - name: Conditional run
        if: Contains(steps.filepath.outputs.commitpath, 'pretty.json')
        run: |
          echo HELLO
