name: Show payload

on:
  push:
    branches:
      - 'payload'

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Show payload
        run: |
          jq '.' $GITHUB_EVENT_PATH

      - name: Show size
        run: |
          echo "${{ github.event }}"
          echo "${{ github.event.ref }}"
          echo "${{ github.ref }}"
          echo "${{ github.event.size }}"
          echo "${{ github.event.push.size }}"
          echo "${{ github.event.push.*.size }}"
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          #ref: ${{ github.event.ref }}
          path: 'testing'
          #fetch-depth: ${{ github.event.size }}
      - name: Run only
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}  
        working-directory: ./testing
      - name: Export changed
        id: filepath
        run: |
          echo ::set-output name=commitpath::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
        working-directory: ./testing
      - name: Show changed paths
        run: |
          echo ${{ steps.filepath.outputs.commitpath }}

      - name: Conditional run
        if: Contains(steps.filepath.outputs.commitpath, 'pretty.json')
        run: |
          echo HELLO
