name: Show payload

on:
  push:
    branches:
      - 'payload'

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Show payload
        run: |
          jq '.' $GITHUB_EVENT_PATH
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Export changed
        id: filepath
        run: |
          echo ::set-output name=commitpath::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
      - name: Show changed paths
        run: |
          echo ${{ steps.filepath.outputs.commitpath}}
