name: Ping other repository on push

on:
  push:
    branches:
      - mk-docs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Gignal by the message
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.CERNA_TOKEN }}
        repository: cerna/cerna.github.io
        event-type: rebuild-site-now
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "authorization": "lanovka"}'