name: Ping other repository on push

on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    # This simple to is used for inter-repository signaling

    steps:
    - name: Signal other repository by the message
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets. MACHINEKITBOT_TOKEN }}
        repository: cerna/cerna.github.io
        event-type: rebuild-site-now
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "authorization": "${{ secrets.KEYCODE }}"}'