name: Ping this

on:
  pull_request:
    branches:
      - mk-docs

jobs:
  build:

    runs-on: ubuntu-latest

    # This simple to is used for inter-repository signaling

    steps:
    - name: Signal other repository by the message
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.CERNA_TOKEN }}
        repository: cerna/cerna-testing-actions
        event-type: test-ping
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      env:
        GITHUB_ACTOR: 'cerna'