name: Test python Cloudsmith

on:
  push:
    branches:
    - '*'

jobs:
  pythonTest:
    name: Python test
    runs-on: ubuntu-latest

    steps:
    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    
    - name: Install Cloudsmit CLI
      run: |
        pip3 install --upgrade cloudsmith-cli
    
    - name: Test Cloudsmith CLI
      run: |
        cloudsmith help

    - name: Cloudsmith CLI whoami
      run: |
        cloudsmith whoami
      env:
        CLOUDSMITH_API_KEY: '${{ secrets.CLOUDSMITH_API_KEY }}'
    
    - name: kontejner
      uses: docker://python:3.8.2-alpine3.11
      with:
        args: python --version

    - name: kontejner2
      uses: docker://python:3.8.2-alpine3.11
      env:
        CLOUDSMITH_API_KEY: '${{ secrets.CLOUDSMITH_API_KEY }}'
      with:
        args: |
          pip3 install --upgrade cloudsmith-cli
  
  pythonC:
    name: kontejner
    runs-on: ubuntu-latest
    container: 
      image: python:3.8.2-alpine3.11
        
    steps:
    - run: |
        pip3 install --upgrade cloudsmith-cli
    - run: cloudsmith help
    - run: cloudsmith whoami
      env:
        CLOUDSMITH_API_KEY: '${{ secrets.CLOUDSMITH_API_KEY }}'
